### ISSUE TITLE
stops working on cycling power

### ISSUE THREAD

**Issue by ajayiyer1** [subpos/esp_firmware_v2#2]
Hi,
The beacons are not showing up in the android app when i disconnect them from my laptop and supply external power.  
The lights go on when i set the module to enable beacon mode (AT+CWSAPEN), however they go off when powered off and don't come back on until I type the above command again.  
Am I missing something here?

**Comment by bleckers** [comment]
This is the intended operation. This firmware is designed this way for use with the SubPos Node boards to reduce flash write wearout. If you just want a basic setup, you can use the standard AT firmware from espressif.

I have updated the readme to reflect this.

Unfortunately there is no quick and easy way to modify the code to work otherwise, as it is using a packet buffer for use with the beacon generator, which you would need to populate from flash.

**Comment by ajayiyer1** [comment]
Thanks for the quick response.
